name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: podman
    container: docker.io/library/node:26
    name: Build and deploy

    steps:
      - name: Install deps ⬇️
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Create SSH key 🔑
        uses: https://codeberg.org/act/ssh-auth@v1
        with:
          host-user: ${{ secrets.HOST_USER }}
          host-ip: ${{ secrets.HOST_IP }}
          host-key: ${{ secrets.HOST_PRIVATE_SSH_KEY }}

      - name: Deploy 🚀
        run: |
          host="${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }}"
          dest="~/pages/textwire"
          ssh $host "mkdir -p $dest"
          rsync -avz --delete docs/.vitepress/dist/ ${host}:$dest

      - name: Deploy to pages branch 🪾
        uses: https://github.com/JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          branch: pages
